/** Imported Libraries */
import Head from 'next/head';
import { useEffect, useState } from 'react';

/** Local Files */
import { authEndpoint, clientId, redirectUri, scopes } from '../config_example';
import styles from '../styles/Home.module.css';
import Footer from '../components/footer';
import Artists from '../components/artists';

export default function Home() {
  /** Spotify Token State */
  const [token, setToken] = useState(null);

  /** Checking if we have information */
  useEffect(() => {
    let Token = window.location.hash
      .substring(1)
      .split(/[&]/)
      .reduce(function (i, item) {
        if (item) {
          let j = item.split(/[=]/);
          i[j[0]] = decodeURIComponent(j[1]);
        }
        return i;
      }, {})['access_token'];
    setToken(Token);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {
          (!token &&
          <a
            className="btn btn--loginApp-link"
            href={`${authEndpoint}?client_id=${clientId}&redirect_uri=${redirectUri}&scope=${scopes.join(
              '%20',
            )}&response_type=token&show_dialog=true`}
          >
            Login to Spotify
          </a>
          )  
      }
      {
        (token && <Artists token={token} />)
      }
      </main>
      <Footer/>
    </div>
  );
}
